# Generated by Django 2.1.7 on 2019-04-13 11:27

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AddField(
            model_name='department',
            name='has_child',
            field=jsonfield.fields.JSONField(default=[], verbose_name='子级菜单'),
        ),
        migrations.AddField(
            model_name='mean',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mean',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mean',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mean',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='department',
            field=jsonfield.fields.JSONField(default=[], verbose_name='角色所处分院'),
        ),
        migrations.AlterField(
            model_name='mean',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='mean',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='user.Mean', verbose_name='父菜单'),
        ),
        migrations.RemoveField(
            model_name='roles',
            name='button',
        ),
        migrations.AddField(
            model_name='roles',
            name='button',
            field=models.ManyToManyField(to='user.Mean', verbose_name='按钮'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department', verbose_name='角色所属部门权限'),
        ),
    ]
