# Generated by Django 2.1.7 on 2019-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190413_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='button',
            field=models.ManyToManyField(blank=True, null=True, to='user.Mean', verbose_name='按钮'),
        ),
    ]
