# Generated by Django 2.1.7 on 2019-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190414_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='button',
            field=models.ManyToManyField(to='user.Mean', verbose_name='按钮'),
        ),
    ]
