# Generated by Django 2.1.7 on 2019-04-14 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='table_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联表名称'),
        ),
    ]
