# Generated by Django 2.1.7 on 2019-04-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190414_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='table_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='关联表的id'),
        ),
    ]
