# Generated by Django 2.1.7 on 2019-04-15 22:56

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190414_2056'),
        ('video', '0003_auto_20190414_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='促销封面')),
                ('index', models.SmallIntegerField(default=0, verbose_name='促销展示顺序')),
                ('stop_date', models.DateField(verbose_name='促销结束时间')),
                ('title', models.CharField(max_length=50, verbose_name='首页促销标题')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '首页促销视频表',
                'verbose_name_plural': '首页促销视频表',
            },
        ),
        migrations.CreateModel(
            name='ShowVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('stop_time', models.DateField(verbose_name='展示停止时间')),
                ('show_way', models.SmallIntegerField(choices=[(0, '图片'), (1, '文字')], verbose_name='展示方式')),
            ],
            options={
                'verbose_name': '首页展示表',
                'verbose_name_plural': '首页展示表',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('desc', models.TextField(max_length=100, verbose_name='类别描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='video.VideoCategory', verbose_name='父类')),
            ],
            options={
                'verbose_name': '视频种类表',
                'verbose_name_plural': '视频种类表',
            },
        ),
        migrations.CreateModel(
            name='VideoSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('specification', models.SmallIntegerField(choices=[(0, '标清'), (1, '高清'), (2, '超清')], verbose_name='视频规格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='视频封面图片')),
                ('price', models.FloatField(default=0,  verbose_name='视频价格')),
                ('file', models.FileField(upload_to='', verbose_name='视频文件')),
            ],
            options={
                'verbose_name': '视频SKU表',
                'verbose_name_plural': '视频SKU表',
            },
        ),
        migrations.CreateModel(
            name='VideoSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品留言')),
                ('comment', models.DecimalField(decimal_places=1, default=3.5, max_digits=5, verbose_name='视频评分')),
                ('after_service', models.TextField(verbose_name='商品售后服务')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='商品简介')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.VideoCategory', verbose_name='商品类别')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '视频SPU表',
                'verbose_name_plural': '视频SPU表',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='videosku',
            name='spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.VideoSPU', verbose_name='视频关联SPU表'),
        ),
        migrations.AddField(
            model_name='showvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.VideoCategory', verbose_name='视频分类表'),
        ),
        migrations.AddField(
            model_name='showvideo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='showvideo',
            name='spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.VideoSPU', verbose_name='视频spu表'),
        ),
        migrations.AddField(
            model_name='promotionvideo',
            name='spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.VideoSPU', verbose_name='促销视频'),
        ),
    ]
