# Generated by Django 2.1.7 on 2019-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190415_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosku',
            name='price',
            field=models.FloatField(default=0, verbose_name='视频价格'),
        ),
        migrations.AlterUniqueTogether(
            name='videosku',
            unique_together={('spu', 'specification')},
        ),
    ]
