# Generated by Django 2.1.7 on 2019-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20190425_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='订单编号'),
        ),
    ]
