"""
Django settings for Fresh_every_day project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(1,os.path.join(BASE_DIR,'api'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q_b_h3yx)6+_+u)##a!)vc%$xa!$m9zc6!33e9h036))^^(j3c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_URL ='/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'user.apps.UserConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Fresh_every_day.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fresh_every_day.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Fresh_every_day_db',
        'HOST': '192.168.187.132',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'oracle',
        #使用mysql的innodb引擎,MyISAM虽快但没有事务rollback
        'OPTIONS':{'init_command':'SET default_storage_engine=INNODB;'},
    },
    # #配置数据库slave节点机
    # 'slave': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'HOST': '127.0.0.1',
    #     'PORT': 3306,
    #     'USER': 'root',
    #     'PASSWORD': 'oracle',
    #     'NAME': 'Fresh_every_day_db'
    # }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

#设置可以跨域访问
CORS_ORIGIN_ALLOW_ALL=True

#跨域所能请求的域名
CORS_ORIGIN_WHITELIST = (
    '*',
)

AUTH_USER_MODEL='user.User'

AUTHENTICATION_BACKENDS = (
    'utils.authentication.UserModelBackend',
)

REST_FRAMEWORK=\
    {
    # #设置所有接口都需要验证
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    #                               ),
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'utils.authentication.TokenAuthentication',
                                        ),
    #'UNAUTHENTICATED_USER':lambda :'匿名用户'
    # 'DEFAULT_THROTTLE_CLASSES': (
    # 'rest_framework.throttling.AnonRateThrottle',
    # 'rest_framework.throttling.UserRateThrottle'
    #                           ),
    # 'DEFAULT_THROTTLE_RATES': {
    # 'anon': '1/minute',
    # 'user': '1/minute'        },
    }

FERNET_TOKEN ={
            "KEY": b"_NIHq7FBB6oUBXeteylToGBqt09QxobBdXtBFSxnSCY=",
            }
ItsDangerousToken={
            'KEY':'xxx'
            }
TOKEN_FILEDS=('username','is_admin')
TOKEN_EXPIRS=1000

CACHES = {
    'default': {
        'BACKEND': "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.187.132:6379/1",
        'TIMEOUT':600,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                    }
                },
    'user': {
        'BACKEND': "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.187.132:6379/10",
        'TIMEOUT':600,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                    }
                },
}

SMS_CONF={'data':"""
        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
            <s:Body>
                <SendMessage3 xmlns="http://openmas.chinamobile.com/sms">
                    <destinationAddresses xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays"
                                          xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                        <a:string>{mobile}</a:string>
                    </destinationAddresses>
                    <message>【我的私人项目】亲爱的{user}，您的验证码是{code}。有效期为{min}，请尽快验证</message>
                    <extendCode>5</extendCode>
                    <applicationId>zzb3</applicationId>
                    <password>VBunGt5VLv4V</password>
                </SendMessage3>
            </s:Body>
        </s:Envelope>
        """,
        'url':'http://111.1.18.21:9080/OpenMasService',
        'headers':{
              'Content-Type': 'text/xml',
              'SOAPAction': 'http://openmas.chinamobile.com/sms/ISms/SendMessage3'
                    }
        }
SMS_EXPIRS=1000
REGEX_MOBILE = "^1[358]\d{9}$|^147\d{8}$|^176\d{8}$"

REDIS_HOST = 'redis://192.168.187.132:6379/'
BROKER_BACKEND = "redis"
BROKER_URL = REDIS_HOST + "8"
REDIS_CONNECT_RETRY = True
CELERY_SEND_EVENTS = True
CELERY_RESULT_BACKEND = 'redis'
CELERY_TASK_RESULT_EXPIRES = 10
CELERYBEAT_SCHEDULER = "djcelery.schedulers.DatabaseScheduler"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 31104000}
CELERY_DEFAULT_QUEUE = 'default'
CELERY_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_DEFAULT_ROUTING_KEY = 'default'
CELERY_IMPORTS = ('user.celery',)